/** 圆的半径的单位系数 @type {*} */
const RADIUSUNIT = 1000

const DEFAULTTYCODE = 'DEFAULT'
const DEFAULT_TYPHOON_ID = -1

/** @type {*} 默认的台风时间戳*/
const DEFAULTTIMESTAMP = '000000'

export { RADIUSUNIT, DEFAULTTYCODE, DEFAULTTIMESTAMP, DEFAULT_TYPHOON_ID }
